spring:
  application:
    name: aoc2019
  config:
    import: optional:file:.env[.properties]

aoc:
  session-cookie: ${AOC_SESSION}

logging:
  level:
    rolfrander.aoc2019.Intcode: INFO
    # used for logging individual instructions of the VM ASM
    rolfrander.aoc2019.Intcode.INSTR: INFO
    rolfrander.aoc2019.Day07: DEBUG
  pattern:
    console: "%-5level [%logger{20}] %msg%n"
